### ISSUE TITLE
DRM Content Listeners

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#12]
Is there any Listener which tells me if the content is expired?
also let me know while playing the content if its get expired how do i come to know ?

**Comment by ravirajjak** [comment]
@matamegger any update on this.
You guys are very slow in responding. 
we are your paid customers.

**Comment by LudoMichaud** [comment]
Hi @ravirajjak 
The `OfflineContentManager` will throw a `DrmLicenseKeyExpiredException` when calling `getOfflineSourceItem` and the DRM content is already expired.
Additionally it is possible to call `getRemainingOfflineLicenseDuration` to check the status any time.

If the content is expired a simple call to `renewOfflineLicense`, will update the license and the content should be playable again.

**Comment by ravirajjak** [comment]
@LudoMichaud
As per your sample code in Android of OfflinePlayback Sample.
In MainActivity I found DrmLicenseKeyExpiredException  i get this exception. What about continuous play of a video and in between it get stop due to license expiry. I dont get any event listener for that. I get exception thrown from  bimovin sdk. Where am I suppose to catch you have not mentioned in PlayerUi.class ?
I hope you are getting me
I just want to catch event when a user plays a video and get exception.

**Comment by SInCE** [comment]
As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue.

If this isn't the case, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. Thank you very much for your understanding!
