### ISSUE TITLE
Chrome Cast Subtitle Issue

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#17]
## Describe the bug
Whenever I try to cast video I am not able to see subtitle while video is casted.

## Behavior
**Actual:** On  Click of cast video should play with subtitle
**Expected:** No subtitle visible

Bitmovin SDK 2.13

**Comment by SInCE** [comment]
Hi, thanks for reaching out! As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue.

If you are still observing this problem with our [latest Android SDK version](https://bitmovin.com/docs/player/releases/android) and the BasicCasting example of this repository or your own app implementation , **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. 

In your request please make sure to provide 
- the Chromecast version you used
- the Android SDK you were using
- An example + Content and instructions for our team so they can reproduce the issue accordingly in order to investigate it.
- any further details you consider to be helpful to replicate the problem accordingly.

Thank you very much for your understanding!
