### ISSUE TITLE
Subtitle Issue

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#20]
@dweinber @matamegger @LudoMichaud How to change dynamically subtitle ? I have few url of subtitle english and german.
How to change subs while playing a video?

**Comment by SInCE** [comment]
Hi Ravi,

You can dynamically add subtitle tracks using the `PlayerAPI` of the SDK and its `addSubtitleTrack` method ([link](https://bitmovin.com/files/native-sdk-documentation/android/2.19.0/com/bitmovin/player/api/PlayerAPI.html#addSubtitle-com.bitmovin.player.config.track.SubtitleTrack-)). In order to programmatically select a specific subtitle that shall be shown, you can use the the `setSubtitle` ([link](https://bitmovin.com/files/native-sdk-documentation/android/2.19.0/com/bitmovin/player/api/PlayerAPI.html#setSubtitle-java.lang.String-)) method accordingly.
To determine the `trackID` of a subtitle, you can use the `getAvailableSubtitles` method accordingly. I hope this is helpful. All available API call are shown in the [API reference of our Android SDK](https://bitmovin.com/android-sdk-documentation/).

The `customUiSubtitleView` [example](https://github.com/bitmovin/bitmovin-player-android-samples/blob/master/CustomUiSubtitleView/src/main/java/com/bitmovin/player/samples/custom/ui/subtitleview/PlayerControls.java#L171), shows how these methods can be used.

If you any further questions about how to use the SDK, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. Thank you very much for your understanding!
