### ISSUE TITLE
DRM Content playlist example

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#25]
I wanted to know how can we play DRM Content as a PlayList Item.
As per the example its normal MPD url. Also the DRM Configuration is set before playing the video.
How can we set DRM Config while playing the video?

**Comment by SInCE** [comment]
Hi, thanks for reaching out! 

The DRM configuration has to be known upfront the playback and can't be applied during the playback of the content. The reason is simply that the DRM solution needs to be initialised first, so the content can be decrypted accordingly.

In order to be able to use the PlaylistItem class for DRM content as well, you would have to extend its definition, which is part of the example [here](https://github.com/bitmovin/bitmovin-player-android-samples/blob/eacdf906d908808724bd083e49489a5508883c55/BasicPlaylist/src/main/java/com/bitmovin/player/samples/playlist/basic/MainActivity.java#L167), so you can provide it with your DRM configuration as well.
Then you would need to adjust the method with configures the playback accordingly [here](https://github.com/bitmovin/bitmovin-player-android-samples/blob/eacdf906d908808724bd083e49489a5508883c55/BasicPlaylist/src/main/java/com/bitmovin/player/samples/playlist/basic/MainActivity.java#L51), as shown in the [BasicDRMPlayback example ](https://github.com/bitmovin/bitmovin-player-android-samples/blob/master/BasicDRMPlayback/src/main/java/com/bitmovin/player/samples/drm/basic/MainActivity.java#L80).

**Comment by SInCE** [comment]
If you have any questions about using our SDK's or about our services, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at [support@bitmovin.com](mailto:support@bitmovin.com). Thank you very much for your understanding!
