### ISSUE TITLE
PIP not supporting on API27

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#26]
PIP is not supported on API 27.  According to Android Doc API 27 has PIP.
Please verify the issue

**Comment by hawk23** [comment]
PiP is supported on API level 26 and higher.

**Comment by SInCE** [comment]
Hi Ravi, as mentioned by my colleague before PiP support is available since API 26 ([link](https://developer.android.com/about/versions/oreo/android-8.0)). Further we do have a[ PiP example](https://github.com/bitmovin/bitmovin-player-android-samples/tree/master/BasicPiPHandling) available in this repository as well, which should be helpful to understand how to use it :)

As there is no further activity, I assume you have no further questions regarding this topic. Therefore, I'm closing this issue.
