### ISSUE TITLE
Offline Download Video Exceception

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#29]
Getting Exception While Playing Offline Video.
The video is not deleted.
com.bitmovin.player.DrmLicenseKeyExpiredException: No offline DRM data are stored. Possible causes are:
-They have been deleted.
-The license is not allowed to be stored offline and thus doesn't exist.

**Comment by SInCE** [comment]
Hi, thanks for reaching out! Please understand that without any details what you tried and what you used, we can't provide any kind of assistance. 

If you still observe this problem with our [latest Android SDK version](https://bitmovin.com/docs/player/releases/android) used in your own app implementation , **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. 

In your request please make sure to provide 
- the Android SDK you were using
- An example + Content and instructions for our team so they can reproduce the issue accordingly in order to investigate it.
- any further details you consider to be helpful to replicate the problem accordingly.

Thank you very much for your understanding!

**Comment by ravirajjak** [comment]
I have downloaded the video in offline.
When i try to get the offline video
that time it gives me that error.
No offline DRM data are stored. Possible causes are:
	-They have been deleted.
	-The license is not allowed to be stored offline and thus doesn't exist.
