### ISSUE TITLE
uriString Null Pointer Exception

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#30]
@dweinber @matamegger 
On offline content play getting NullPointerException uriString
java.lang.NullPointerException: uriString

While passing PlayerConfiguration to BitmovinPlayerView
please tell me what is the issue?

**Comment by ravirajjak** [comment]
@dweinber @matamegger @LudoMichaud 
in some scenario for offline content loading you need poster source.
if I dint provide poster source it throws uristring null pointer exception.
Also when i disconnect from internet it doesnt play video but when i am online it plays the video which is stored offline.
Please look into this issue

**Comment by ravirajjak** [comment]
Why dont you guys put this line in try catch.
Dont you think it will crash the app if no internet connection is there and loading offline data


  if (var1.getPosterSource() != null) {
                var4.addImage(new WebImage(Uri.parse(var1.getPosterSource().getUrl())));
}

**Comment by ravirajjak** [comment]
@jarhoax  Please look into this issue

**Comment by ravirajjak** [comment]
any update?

**Comment by matamegger** [comment]
For faster support please contact us over our support channels support@bitmovin.com .

In order to help you, can you please provide us the full Exception + Stacktrace and the `PlayerConfiguration` or at least the `SourceItem`. Additionally, the steps to reproduce the crash would help.

FYI: The line you are pointing us to, does not make any network calls, so it will not crash because the device is offline.

**Comment by SInCE** [comment]
Hi, thanks for reaching out! Please understand that without any details about what you tried and what you used, we can't provide any kind of assistance. 

If you still observe this problem with our [latest Android SDK version](https://bitmovin.com/docs/player/releases/android) used in your own app implementation , **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. 

In your request please make sure to provide 
- the Android SDK you were using
- the full stacktrace + Exception,
- An example + Content(SourceItem), PlayerConfiguration, and instructions for our team so they can reproduce the issue accordingly in order to investigate it.
- any further details you consider to be helpful to replicate the problem accordingly.

Thank you very much for your understanding!
