### ISSUE TITLE
LIVE content continues over the limit.

### ISSUE THREAD

**Issue by DavidCruzUK** [bitmovin/bitmovin-player-android-samples#70]
**Which sample is this report about?**
- Sample name or link: [Image](https://imgur.com/a/36f3ZjV)

**Describe the bug**
When The player is streaming LIVE content the progress thumb continues after the own limit.
The limit is never passed if you scroll manually to the end.

**To Reproduce**
Steps to reproduce the behaviour:
1. open the player with HLS (*.m3u8) Live Content.
2. wait for few around 10 seconds after content starts to notice the bug
3. Notice the bar goes after the limit expected.

**Expected behaviour**
- Progressbar should not continue progressing after the end, and Live red dot should be highlighted.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 10, Samsung galaxy note 8, Samsung Galaxy J6
 - OS: Android
 - Version:  8.0 to 10

**Additional context**
The bug could be reproduced almost in any device.

**Comment by SInCE** [comment]
Hi David,

despite the time this issue was around unfortunately, the upside is that this behaviour has been addressed already, and can no longer be observed in our latest SDK versions to my understanding. For further assistance please feel free to reach out to our support team as described here: https://github.com/bitmovin/bitmovin-player-android-samples#support 

Thank you very much for your understanding!
