### ISSUE TITLE
How to skip default qualities ?

### ISSUE THREAD

**Issue by uds214125** [bitmovin/bitmovin-player-android-samples#72]
Basically I want to set only three qualities "High", "Medium" and "Low" and other qualities to be remove.

How to add this.

I checked and added labeling option but it is displaying all available qualities.

Thanks

**Comment by SInCE** [comment]
Hi Uds,

`preprocessHttpResponse` could be used to parse the MPD manifest before it gets to the player to trim the quality levels you don't want to be available to the user in the end. 
If you control the content creation as well, the most straightforward way would be to create an MPD manifest that only contains these 3 qualities and nothing else, so you don't have to workaround it on the client side 👍  

For further assistance please feel free to reach out to our support team as described here: https://github.com/bitmovin/bitmovin-player-android-samples#support 

Thank you very much for your understanding!
