### ISSUE TITLE
Android Bitmovin Cast logo Issue

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#8]
When I cast a video from mobile for a DRM or Without DRM Content. I see bitmovin logo on TV.
Is there any method to change it or to remove it?
Bitmovin SDK Version 2.13

**Comment by matamegger** [comment]
With the `receiverStylesheetUrl` property in the `RemoteControlConfiguration` It is possible to change the chrome cast app's CSS.

**Comment by ravirajjak** [comment]
@matamegger  I posted regarding Android Version.

**Comment by matamegger** [comment]
Please consider reading the API documentation: https://bitmovin.com/android-sdk-documentation/
The property must be set with an URL to an CSS file.
Maybe a look at https://github.com/bitmovin/bitmovin-player-ui will also help.

**Comment by ravirajjak** [comment]
@dweinber  The issue still persist please provide me the exact code.
Please update asap

**Comment by dweinber** [comment]
`setReceiverStylesheetUrl` is the URL a CSS file, which should contain the relevant style changes of the UI, such as the watermark image. The exact CSS rule is documented in https://bitmovin.com/docs/player/articles/player-ui-css-class-reference#overlays (`.bmpui-ui-watermark`).

**Comment by hawk23** [comment]
If you modify the player configuration, you need to pass it to the `setup` method of the player to have the changes applied. Instead of grabbing the current configuration from the player by calling `getConfig()`, I'd suggest creating a new `PlayerConfiguration`, setting the desired values there and passing it to setup:
```Java
// Get a reference to the player
this.bitmovinPlayer = this.bitmovinPlayerView.getPlayer();

// Create a new default player configuration and set the desired values
PlayerConfiguration playerConfiguration = new PlayerConfiguration();
playerConfiguration.getRemoteControlConfiguration().setReceiverStylesheetUrl("URL_TO_FILE");
playerConfiguration.getStyleConfiguration().setSupplementalPlayerUiCss("URL_TO_FILE");

// Setup the player with the changed configuration values
this.bitmovinPlayer.setup(playerConfiguration);

// In the initializePlayer method a source should be loaded using the `this.bitmovinPlayer.load()` API call. 
this.initializePlayer(sourceUrl, sourceTitle);
```

Also, please make sure to use `setSupplementalPlayerUiCss` instead of `setPlayerUiCss`, because you just want to add additional style rules. Use `setPlayerUiCss` only if you want to fully replace the default styles.

Please note that in the `initializePlayer` method you should only call `load` on the player. If you call `setup` again, the previous configuration values could be overwritten if you are not careful.

**Comment by dweinber** [comment]
Please note that the Chromecast loads the CSS file from the specified URL, so please make sure that's accessible over the internet. Chromecast won't be able to access local URLs on the Android device.

**Comment by ravirajjak** [comment]
@dweinber  great thanks for the solution its working

**Comment by zack-barakat** [comment]
@3B00D
Check this
